fm_elfinder:
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            path_prefix: http://test.la-roue-libre.com/
            connector:
                debug: true # Désactive le débug
                roots:
                    uploads:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: uploads # Chemin d'upload
                        upload_allow: ['all'] # Fichiers autorisés
                        upload_deny: [''] # Fichiers interdits
                        upload_max_size: 1024M # Taille maximum